version: "3.8"

services:
  app:
    build: .
    container_name: finansys-django-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/django/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: finansys-django-db
    tty: true
    environment:
      - POSTGRES_DB=finansys_django
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "6543:5432"
    volumes:
      - finansys-django-pgdata:/var/lib/postgresql/data

volumes:
  finansys-django-pgdata:
    external: true